### ISSUE TITLE
OwnTone disconnecting from macOS Sonoma "Music" app (or maybe "Music" disconnecting from OwnTone...)

### ISSUE THREAD

**Issue by jimmiedave** [owntone/owntone-server#1712] opened 2024-01-19 03:17 UTC
Music and OwnTone become disconnected after successfully sharing music from the server for a bit. It appears that the disconnect occurs while OwnTone is paused during or stopped after playback.

Mac is on power and set not to sleep while powered - though it will shut off the display.

Disconnect occurs after some time - it's not instantaneous.

Does not appear to drop connection while playing

owntone.log shows server starts, cache updates, no obvious trouble.

To repro (as far as I know now)
- Connect Music.App to DAAP sharing on the OwnTone server. Start playing something. Pause it or allow it to end. Go away for some indeterminate time. Return and note that Music.App is disconnected from OwnTone server. Reconnect to the server (you can do so) and note that you can play music (though the song you might've been paused in isn't queued up (expected behavior there)).

- Disconnection can happen within perhaps 20 minutes (did so while I was away for no more than 20)
- Music.app running on Sonoma 14.2.1 on an Intel 2019 MacBook Pro 16in with 16GB RAM, plenty of free disk.
- Same owntone server and software, same Mac unit running Catalina before upgrading to Sonoma, Music.app operated without disconnects.

- owntone-28.8 - built locally on the Raspberry Pi music server
- Raspberry Pi 4, 4GB, Debian Bookworm (yes, really Debian, not RasPiOS)

```
## --------- ##
## Platform. ##
## --------- ##

hostname = bistromath
uname -m = aarch64
uname -r = 6.1.0-17-arm64
uname -s = Linux
uname -v = #1 SMP Debian 6.1.69-1 (2023-12-30)

```

Debug log below:
After turning log level to debug, restarting owntone, I connected with Music.app, played one song (selected from a server playlist), waited for Music  to  advance to the next. That's when the log started repeating that the connection had closed. I waited for quite a while (the Music.app interface didn't show the disconnection - unlike what I've been experiencing). I eventually pressed  the "next track" button on Music.app, and on the Mac got the "Connecting..."  dialog with the progress bar. No progress, no connection, no crash, no new entries in the log file.

[owntone.log](https://github.com/owntone/owntone-server/files/13984156/owntone.log)

**Comment by ejurgensen** [comment] 2024-01-19 13:55
Thanks for a good report. I don't have a Mac, but I'll see if it reproduces with iTunes. If not, it won't be easy, because there are no clues in the log. It just a disconnection.

**Comment by hacketiwack** [comment] 2024-01-19 15:05
> How does one "Connect Music.App to DAAP sharing on the OwnTone server"? I've got a Mac but it's not obvious how to access owntone from Music.

That's the magic of the no so great UX of Apple Music application. On the left menu bar, you should have the name of your local music library. When you click on its name, you should have a list of other music libraries available on the network. See below.

<img width="226" alt="Change Music Library Source" src="https://github.com/owntone/owntone-server/assets/13329768/64e9440d-5f9c-4df8-91e3-764818240d02">

**Comment by hacketiwack** [comment] 2024-01-19 15:07
> Thanks for a good report. I don't have a Mac, but I'll see if it reproduces with iTunes. If not, it won't be easy, because there are no clues in the log. It just a disconnection.

@ejurgensen if you want a macOS virtual machine, I can prepare one for you.

**Comment by ejurgensen** [comment] 2024-01-19 15:18
That would be awesome! Then I can also look at the libwebsockets issue.

**Comment by hacketiwack** [comment] 2024-01-19 15:29
> Can you make it for vmware?

OK. I will try to make you that. 😉

**Comment by jimmiedave** [comment] 2024-01-19 15:50
> > How does one "Connect Music.App to DAAP sharing on the OwnTone server"? I've got a Mac but it's not obvious how to access owntone from Music.
> 
> That's the magic of the no so great UX of Apple Music application. On the left menu bar, you should have the name of your local music library. When you click on its name, you should have a list of other music libraries available on the network. See below.
> <img alt="Change Music Library Source" width="226" src="https://private-user-images.githubusercontent.com/13329768/298108238-64e9440d-5f9c-4df8-91e3-764818240d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk0NjcsIm5iZiI6MTcwNTY3OTE2NywicGF0aCI6Ii8xMzMyOTc2OC8yOTgxMDgyMzgtNjRlOTQ0MGQtNWY5Yy00ZGY4LTkxZTMtNzY0ODE4MjQwZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE1NDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjQ1N2FjOTA0YWEyZGUyZWY1M2QzNzMxYTJlZjZiZjUxYzdhYjE0ZGMxYTNiYTdmMGQ2ZGM1NTVkNDMwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BgZ2SFeo9bzHbQmMfnMjXRjKp4RIS743oPRuw4roSTI">

That's right, but there's even MORE not-so-great-UX: If you're on Catalina (at least) and the Music.app window is too close to a left-hand "space" edge (may or may not have to be lined right up to the edge), you can't even get that menu to  appear - even if everything else is working right. Seems fixed on Sonoma. I didn't make any of the intermediate upgrades. I fought with this as a long time and even filed it as an owntone bug (server never appears) before figuring out it was an Apple UI thing.

**Comment by frankusb** [comment] 2024-01-19 16:53
> That's the magic of the no so great UX of Apple Music application. On the left menu bar, you should have the name of your local music library. When you click on its name, you should have a list of other music libraries available on the network. See below.

That's evil. But it works. Thanks.

**Comment by ejurgensen** [comment] 2024-01-19 21:19
I've tried for a couple with hours with iTunes, and it didn't disconnect

**Comment by jimmiedave** [comment] 2024-01-19 22:15
I've been timing sessions today, trying a few different things to see what it might take to repro: no disconnects either. I may have to close this as "random space junk". But will try and repro again for a while.

**Comment by frankusb** [comment] 2024-01-19 22:22
It just disconnected for me. I played 1 full song and part of a second and then closed the Music window although it was still running. It was less than 10 minutes and when I brought the window back it was disconnected. Nothing in the owntone log.

**Comment by jimmiedave** [comment] 2024-01-20 01:15
I should mention that a WiFi disconnect will demonstrate the symptoms I mentioned first, though I've got really good WiFi 6 signal, and am about 8 feet diagonally (through the floor) from the antennae of the router.

**Comment by frankusb** [comment] 2024-01-20 01:24
I despise wireless so my tests have been wired only.

**Comment by jimmiedave** [comment] 2024-01-20 05:23
This evening, hooked up Music.app to owntone at 9PM almost on the dot. Played some music and paused it. I don't know when, but  by 12:25AM it had disconnected.

**Comment by ejurgensen** [comment] 2024-01-20 08:25
Can you listen to the traffic with Wireshark? Set it to listen to port 3689. Maybe what precedes the disconnect could provide a clue.

**Comment by jimmiedave** [comment] 2024-01-22 02:43
I'll try and get that happening this week (a few other important things going on; worried this will turn into a Yak Shave).

I'll have to bumble through the setup. I understand the concepts of packet capture, port, etc. but will be starting from scratch with the Wireshark (4.0) UI.

**Comment by jimmiedave** [comment] 2024-01-23 03:38
Here's a wireshark capture. Packet 3439 is where Music.app was paused. It sat there paused all afternoon and into the evening, without a disconnect. Let me know if this is what you're after.
[Cap240122.txt](https://github.com/owntone/owntone-server/files/14017996/Cap240122.txt)

**Comment by ejurgensen** [comment] 2024-01-23 07:46
I understand there wasn't a disconnect? It was only the communication right before a disconnect I was interested in.

**Comment by ejurgensen** [comment] 2024-01-23 11:56
Also please share it in Wireshark's format (pcap/pcapng).

**Comment by jimmiedave** [comment] 2024-01-23 17:03
I realize you'd like a disconnect in the packets. Just didn't have one yesterday. I have Music.app paused and Wireshark running, and will run all day (unless I capture a disconnect). I've figured out how to export pcapng files now.

**Comment by jimmiedave** [comment] 2024-01-24 04:38
Another full day, no disconnect, though monitored on pause all day. Can't fix something if it won't stay broken.

I'm not going to file daily reports, but instead will post here when I have something to show.

**Comment by X-Ryl669** [comment] 2024-01-26 15:30
Are you sure it isn't your Mac that's powering off the network device when it enters sleep ? That would explain that you don't get any disconnect while Wireshark is running since it prevents going to sleep.

The Apple UI is awful and misleading to disable this "feature". Look [here] for the "Battery" screenshot. 
You have to toggle the "Enable power nap" feature to the opposite of what you understand when you read it (don't remember what is the right setting, just toggle it if it doesn't work and magically, it works).

**Comment by jimmiedave** [comment] 2024-01-26 18:03
> Are you sure it isn't your Mac that's powering off the network device when it enters sleep ? That would explain that you don't get any disconnect while Wireshark is running since it prevents going to sleep.

Well, the machine's on-power and set not to sleep at all when on power. I recognize what power nap does, but it's not in scope if there's no sleeping at all.

However, I'm aware that there could be external events causing the disconnects I've seen. I've got a pretty stable internal network, and am close to a strong WiFi router. I thought I might've caught a disconnect yesterday - only to realize I'd rebooted the router due to struggling over poor internet connectivity (Actually, Comcrap was pulling wires across the street).

So yeah, maybe "we has found the enemy, and he is us" to quote Pogo. I'll monitor for a few more days, and if I can't find or cause anything, I'll give it up.

**Comment by jimmiedave** [comment] 2024-01-29 15:38
Got one. Pretty brief this AM. Cold booted machine to Sonoma 14.2.1, opened Music, connected to server (on 10.2.4.100) - interestingly, seemed like it might've taken two tries to connect - that is not logged anyplace, not sure if it happened. After connected and settled, turned on Wireshark. Put on "Ants from Up There" by Black Country New Road, played the first 2-3 songs, paused Music.app. Started capturing packets. Walked away from the machine for a little while - long enough to play the screen saver (ISS Earth - All) and for the screen to turn off (it's disabled from sleeping while on power, which it's been since boot).

Enclosed are a screen grab from my power/sleep settings, and a packet capture. Looks like Music.app is trying to log out via http. WTH‽

<img width="594" alt="Screenshot 2024-01-29 at 10 29 27 AM" src="https://github.com/owntone/owntone-server/assets/35353530/bacaa63c-f0be-4c74-8c64-1b908ea7a9be">

[Sonoma_music-app_disconnect.pcapng.zip](https://github.com/owntone/owntone-server/files/14086363/Sonoma_music-app_disconnect.pcapng.zip)

**Comment by jimmiedave** [comment] 2024-01-29 17:15
Well, don't know how much capture you want - it's huge when I load the libraries and play stuff.

This capture covers - I don't know, maybe 30 minutes?

I don't start capture 'til it's loaded (and packets keep coming after it's apparently loaded - I think it's lazyloading all the playlists in the background or something), and a track is paused. That means there are no packets flying around except the eventual and occasional "are you there" and ACK. After starting capture, it's been able to go 8 hours plus without anything but the above couple packets. Stop capture because I'm done for the day or have to reboot or something.

One thing I've asked myself: I have an Applescript that sets up all my views for my server playlists (want it in "View: as Songs" and showing Column Browser), and since the update to Sonoma's Music.app, it starts, selects the first playlist and fails, gives me an alert. I dismiss the alert. **But**, I've run this every time, including full days with no disconnects, so I think that's not it.

Failure alert
<img width="265" alt="Screenshot 2024-01-29 at 12 06 40 PM" src="https://github.com/owntone/owntone-server/assets/35353530/1f5e53df-b94c-43f2-93be-fcdfff416982">

The line that's failing
<img width="670" alt="Screenshot 2024-01-29 at 12 13 52 PM" src="https://github.com/owntone/owntone-server/assets/35353530/948dc103-403b-444d-b520-517faca89ef0">

I don't think that Applescript can (or that it _is_ in this case) leave stuff open and unclean in Music.app

**Comment by ejurgensen** [comment] 2024-01-29 18:09
> The previously enclosed capture covers - I don't know, maybe 30 minutes?

Just the preceding 10-20 secs. If something is making Music.app disconnect, I'm sure it has happening right before. If there is nothing, then it can't be anything that OwnTone is doing that is causing the disconnect.

I have no idea about the Applescript.

**Comment by jimmiedave** [comment] 2024-01-29 18:25
No, minutes. Lots of them. The current session has been running for maybe 40 minutes:

<img width="1731" alt="Screenshot 2024-01-29 at 1 25 12 PM" src="https://github.com/owntone/owntone-server/assets/35353530/fe52ed03-8e55-45dc-9632-93ff3bbf06cc">

**Comment by frankusb** [comment] 2024-01-29 19:13
> I don't think that Applescript can (or that it _is_ in this case) leave stuff open and unclean in Music.app

I don't have any Applescript that interacts with Music and did experience the disconnect so I doubt it's related.

**Comment by jimmiedave** [comment] 2024-01-30 04:06
Same session that started maybe 8 hours and 40 minutes ago. Music.app has not disconnected and there's no traffic.

If I understand you correctly, if there's no traffic before the disconnect (and in the prior packet capture, there was none immediately before - it'd been running with no traffic for maybe 30 minutes since I got Music.app set up and on the server and settled down), there's nothing owntone is doing, and this is a Music.app-initiated problem.

Is it possible to test a compiled-here version that ignores a disconnect? If that were to remedy things, would it be possible to set a config variable to ignore disconnects from Music.app?

<img width="1742" alt="image" src="https://github.com/owntone/owntone-server/assets/35353530/79227fdb-0af7-4701-bac2-b01bdbc7f1e2">

**Comment by ejurgensen** [comment] 2024-01-30 09:18
> Is it possible to test a compiled-here version that ignores a disconnect, or maybe returns a 400-series error or something? If that were to remedy things, would it be possible to set a config variable to ignore disconnects from Music.app?

I'm not sure what you mean by this? If a client disconnects, then it disconnects. A server can't "ignore" that.

I will close the issue since it seems this isn't an OwnTone issue.

**Closed by ejurgensen** 2024-01-30 09:18 UTC
