### ISSUE TITLE
OwnTone stops responding after interrupting playback with API call

### ISSUE THREAD

**Issue by peterhajas** [owntone/owntone-server#1219] opened 2021-04-02 15:40 UTC
I use OwnTone (great new name, by the way!) connected to several HomePods and other AirPlay devices in my home. I have it configured in a podman container on a Manjaro box. I'm running version 27.4.

I noticed that after triggering playback of an item from a URL, the web UI and server stop responding to input until I restart the container. This request is coming from HomeAssistant's text-to-speech functionality exposed by their [integration](https://www.home-assistant.io/integrations/forked_daapd/).

I enabled the `debug` log level, and captured OwnTone in-state. Here's the request to pause the current media (nothing was playing at the time, which may be the cause of the error):

```
[2021-04-02 08:27:13] [DEBUG]      web: JSON api request: '/api/player/pause'
[2021-04-02 08:27:13] [  LOG]      web: Error pausing playback.
[2021-04-02 08:27:13] [  LOG]      web: JSON api request failed with error code 500 (/api/player/pause)
```

Then, the play command comes in from HA:

```
[2021-04-02 08:27:21] [DEBUG]      web: JSON api request: '/api/queue/items/add?uris=http://192.168.0.139:8123/api/tts_proxy/10e7f43035e5896d2cb76fe339b5f4b0ac023eb8_en_-_google_translate.mp3&playback=start&clear=true'
[2021-04-02 08:27:21] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-04-02 08:27:21] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'queue_version';'
[2021-04-02 08:27:21] [DEBUG]       db: Running query 'DELETE FROM queue where id <> 0;'
[2021-04-02 08:27:21] [DEBUG]       db: Running query 'INSERT OR REPLACE INTO admin (key, value) VALUES ('queue_version', '26');'
[2021-04-02 08:27:21] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-04-02 08:27:21] [DEBUG]      mpd: Asynchronous listener callback called with event type 2.
[2021-04-02 08:27:21] [DEBUG]      mpd: Notify clients waiting for idle results: 2
[2021-04-02 08:27:21] [DEBUG]   player: Player status: stopped
[2021-04-02 08:27:21] [DEBUG]      lib: Add items for path 'http://192.168.0.139:8123/api/tts_proxy/10e7f43035e5896d2cb76fe339b5f4b0ac023eb8_en_-_google_translate.mp3' to the queue
[2021-04-02 08:27:21] [DEBUG]   ffmpeg: Starting connection attempt to 192.168.0.139 port 8123
[2021-04-02 08:27:21] [DEBUG]   ffmpeg: Successfully connected to 192.168.0.139 port 8123
[2021-04-02 08:27:21] [DEBUG]   ffmpeg: Skipping 0 bytes of junk at 1140.
[2021-04-02 08:27:21] [ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[2021-04-02 08:27:21] [DEBUG]     scan: File has 1 streams
[2021-04-02 08:27:21] [DEBUG]     scan: Duration 3960 ms, bitrate 34 kbps, samplerate 24000 channels 1
[2021-04-02 08:27:21] [DEBUG]     scan: MP3
[2021-04-02 08:27:21] [DEBUG]     scan: Picked up 0 tags from file metadata
[2021-04-02 08:27:21] [DEBUG]     scan: Picked up 0 tags with extra md_map
[2021-04-02 08:27:21] [DEBUG]     scan: Picked up 0 tags from file metadata
[2021-04-02 08:27:21] [DEBUG]     scan: Picked up 0 tags with generic md_map, 0 tags total
[2021-04-02 08:27:21] [DEBUG]   ffmpeg: Statistics: 16980 bytes read, 0 seeks
[2021-04-02 08:27:21] [ WARN]     scan: ffmpeg/libav could not extract any metadata
```

but that's it. There are no failures in the log - I've attached the full log to this issue. I'm also unable to send requests via `curl`, like this one to play pop music:

```
curl -X POST "http://MY_DAAPD_SERVER/api/queue/items/add?limit=10&clear=true&playback=start&expression=genre+is+%22Pop%22+order+by+random+desc"
(this never returns)
```

[owntone_stops_responding.txt](https://github.com/owntone/owntone-server/files/6250182/owntone_stops_responding.txt)

Here are the steps to reproduce, which I understand are a bit nuanced:

1. Install and configure [Home Assistant](http://home-assistant.io)
2. Enable TTS in your HA configuration by adding these lines to your `configuration.yaml`:

```
tts:
  - platform: google_translate
    service_name: google_say
```

3. Enable the forked-daapd integration (mine auto-detected)
4. Call the TTS service. I have this one in my `scripts.yaml`:

```
 tts_demo:
  alias: TTS Demo
  sequence:
  - service: tts.google_say
    data:
      entity_id: media_player.forked_daapd_server
      message: Hello this is a test. End of message.
  mode: single
```

**Comment by ejurgensen** [comment] 2021-04-02 17:31
Thanks for a good report. The symptoms sound like a deadlock, but since there is plenty of logging after the error it might not be. So what's causing it is a tough one. The steps to reproduce are a bit too much effort  for me, and I couldn't reproduce by imitating the JSON requests. Perhaps if you could find a simpler way to reproduce?

**Comment by peterhajas** [comment] 2021-04-02 19:22
I'm also unable to reproduce with some JSON API calls that mimic what HA does. I tried feeding the server with lots of repeated play commands, and it still remained functional. I did some more testing, and found that the issue only happens intermittently. Once it does happen, OwnTone stops responding to events.

In the latest reproduction of the issues, I see the same flow of events: adding AirPlay devices, followed by notify callback reasons 11, 78, and 4:

```
[2021-04-02 12:16:00] [DEBUG]     mdns: Avahi Resolver: resolved service 'Office' type '_airplay._tcp' proto 0, host Office.local, address 192.168.0.155
[2021-04-02 12:16:00] [DEBUG]     mdns: Connection test to 192.168.0.155:7000 completed successfully
[2021-04-02 12:16:00] [DEBUG]  airplay: Event for AirPlay device 'Office' (port 7000, id d4a33d6fe519)
[2021-04-02 12:16:00] [ INFO]  airplay: Adding AirPlay device 'Office': features 0x4A7FCA00,0x3C354BD0, type HomePod, address 192.168.0.155:7000
[2021-04-02 12:16:00] [DEBUG]     mdns: Avahi Resolver: resolved service 'Office' type '_airplay._tcp' proto 0, host Office.local, address 192.168.0.155
[2021-04-02 12:16:00] [DEBUG]     mdns: Connection test to 192.168.0.155:7000 completed successfully
[2021-04-02 12:16:00] [DEBUG]  airplay: Event for AirPlay device 'Office' (port 7000, id d4a33d6fe519)
[2021-04-02 12:16:00] [ INFO]  airplay: Adding AirPlay device 'Office': features 0x4A7FCA00,0x3C354BD0, type HomePod, address 192.168.0.155:7000
[2021-04-02 12:16:01] [DEBUG]     mdns: Avahi Resolver: resolved service 'Bedroom' type '_airplay._tcp' proto 0, host Bedroom.local, address 192.168.0.141
[2021-04-02 12:16:01] [DEBUG]     mdns: Connection test to 192.168.0.141:7000 completed successfully
[2021-04-02 12:16:01] [DEBUG]  airplay: Event for AirPlay device 'Bedroom' (port 7000, id d4a33d63f03d)
[2021-04-02 12:16:01] [ INFO]  airplay: Adding AirPlay device 'Bedroom': features 0x4A7FCA00,0x3C356BD0, type HomePod, address 192.168.0.141:7000
[2021-04-02 12:16:01] [DEBUG]     mdns: Avahi Resolver: resolved service 'Bedroom' type '_airplay._tcp' proto 0, host Bedroom.local, address 192.168.0.141
[2021-04-02 12:16:01] [DEBUG]     mdns: Connection test to 192.168.0.141:7000 completed successfully
[2021-04-02 12:16:01] [DEBUG]  airplay: Event for AirPlay device 'Bedroom' (port 7000, id d4a33d63f03d)
[2021-04-02 12:16:01] [ INFO]  airplay: Adding AirPlay device 'Bedroom': features 0x4A7FCA00,0x3C356BD0, type HomePod, address 192.168.0.141:7000
[2021-04-02 12:16:01] [DEBUG]     mdns: Avahi Resolver: resolved service 'D4A33D63F03D@Bedroom' type '_raop._tcp' proto 0, host Bedroom.local, address 192.168.0.141
[2021-04-02 12:16:01] [DEBUG]     mdns: Connection test to 192.168.0.141:7000 completed successfully
[2021-04-02 12:16:01] [DEBUG]     raop: Event for AirPlay device 'Bedroom' (port 7000, id d4a33d63f03d)
[2021-04-02 12:16:01] [ INFO]     raop: Adding AirPlay device 'Bedroom': password: 0, verification: 0, encrypt: 0, authsetup: 0, metadata: 7, type HomePod, address 192.168.0.141:7000
[2021-04-02 12:16:01] [DEBUG]     mdns: Avahi Resolver: resolved service 'D4A33D63F03D@Bedroom' type '_raop._tcp' proto 0, host Bedroom.local, address 192.168.0.141
[2021-04-02 12:16:01] [DEBUG]     mdns: Connection test to 192.168.0.141:7000 completed successfully
[2021-04-02 12:16:01] [DEBUG]     raop: Event for AirPlay device 'Bedroom' (port 7000, id d4a33d63f03d)
[2021-04-02 12:16:01] [ INFO]     raop: Adding AirPlay device 'Bedroom': password: 0, verification: 0, encrypt: 0, authsetup: 0, metadata: 7, type HomePod, address 192.168.0.141:7000
[2021-04-02 12:16:01] [DEBUG]     mdns: Avahi Resolver: resolved service 'D4A33D6FE519@Office' type '_raop._tcp' proto 0, host Office.local, address 192.168.0.155
[2021-04-02 12:16:01] [DEBUG]     mdns: Connection test to 192.168.0.155:7000 completed successfully
[2021-04-02 12:16:01] [DEBUG]     raop: Event for AirPlay device 'Office' (port 7000, id d4a33d6fe519)
[2021-04-02 12:16:01] [ INFO]     raop: Adding AirPlay device 'Office': password: 0, verification: 0, encrypt: 0, authsetup: 0, metadata: 7, type HomePod, address 192.168.0.155:7000
[2021-04-02 12:16:01] [DEBUG]     mdns: Avahi Resolver: resolved service 'D4A33D6FE519@Office' type '_raop._tcp' proto 0, host Office.local, address 192.168.0.155
[2021-04-02 12:16:01] [DEBUG]     mdns: Connection test to 192.168.0.155:7000 completed successfully
[2021-04-02 12:16:01] [DEBUG]     raop: Event for AirPlay device 'Office' (port 7000, id d4a33d6fe519)
[2021-04-02 12:16:01] [ INFO]     raop: Adding AirPlay device 'Office': password: 0, verification: 0, encrypt: 0, authsetup: 0, metadata: 7, type HomePod, address 192.168.0.155:7000
[2021-04-02 12:16:29] [DEBUG]      web: notify callback reason: 11
[2021-04-02 12:16:45] [DEBUG]      web: notify callback reason: 78
[2021-04-02 12:16:45] [DEBUG]      web: notify callback reason: 4
```

If these are the web socket notify callbacks (from `lws_callback_reasons`), then this is:

`LWS_CALLBACK_SERVER_WRITEABLE`
`LWS_CALLBACK_WS_SERVER_DROP_PROTOCOL`
`LWS_CALLBACK_CLOSED`

I'll keep seeing if I can reproduce. Is there any way to capture additional diagnostics while the server is in-state?

**Comment by lox** [comment] 2021-04-26 03:32
I'm seeing this too, using the latest https://github.com/linuxserver/docker-daapd docker image.

**Comment by ejurgensen** [comment] 2021-04-26 14:07
Here some instructions that might help locate the bug (requires gdb):

1. (wait for forked-daapd to freeze)
2. Login and get the pid with `px ax`
3. Run `sudo gdb forked-daapd -p [PID]`
4. Run `info threads`
5. The threads that don't have xxx_poll() are hanging, the trick now is to find out who is waiting for who. I would think player or input are most likely candidates, followed by those called "forked-daapd"
6. Switch to the hanging thread with `thread [thread number]`
7. Run `bt` and share output here. It should reveal what command sequence lead to the deadlock.

Note that I haven't tried this with Docker, so can't say for sure whether this will work.

**Comment by eftimg** [comment] 2021-09-28 18:53
I see this issue as well - similar use case with home assistant, but running owntone 28.1 on Debian 10. Happens a lot more when homepods are playing music and then tts tries to use OwnTone to make an announcement. Music is paused, the announcement may play, or only play part of it, then nothing - I have to restart OwnTone. No errors reported in the logs. If there is no music playing on homepods when OwnTone is used, seems to work much better. I recently updated to 28.2 and haven't had enough time to try it, see if it works better.

**Comment by ejurgensen** [comment] 2021-11-21 08:41
Closing, no feedback

**Closed by ejurgensen** 2021-11-21 08:41 UTC

**Comment by aaronk6** [comment] 2023-11-23 07:03
I think I’m seeing the same issue:

```
Nov 23 04:03:17 homeserver owntone[3268147]: [2023-11-23 04:03:17] [  LOG]     dacp: No session-id specified in request
Nov 23 04:03:17 homeserver owntone[3268147]: [134B blob data]
Nov 23 04:03:36 homeserver owntone[3268147]: [2023-11-23 04:03:36] [  LOG]     dacp: No session-id specified in request
Nov 23 04:03:36 homeserver owntone[3268147]: [157B blob data]
Nov 23 07:00:45 homeserver owntone[3268147]: [2023-11-23 07:00:45] [  LOG]      web: Error starting playback.
Nov 23 07:00:45 homeserver owntone[3268147]: [2023-11-23 07:00:45] [  LOG]      web: JSON api request failed with error code 500 (/api/player/play)
```

I’m also using Home Assistant to control OwnTone via its API.

@ejurgensen, I saw that you shared steps above on how to use gdb to locate the bug. I’ll try this and report back.

**Comment by ejurgensen** [comment] 2023-11-23 12:15
Are you also seeing OwnTone freeze? In that case yes, then gdb can also help locate the issue. Here's a good little guide on how to do that: https://ethanhao.github.io/c++11,/gdb,/multithread,/2017/03/03/Deadlock-detecting-using-GDB-Copy.html

**Comment by aaronk6** [comment] 2023-11-24 11:48
Actually, OwnTone wasn’t frozen. I was somehow able to recover from this state **without a restart**, just using the following steps:

1. Opened OwnTone web interface.
2. Played a track (from a Spotify playlist) – this worked.
3. Went back to Home Assistant and tried playing something from there: Nothing happened (also not getting the error 500 anymore which I could trigger multiple times before).
4. Tried enabling/disabling an OwnTone output in Home Assistant: Nothing happened.
5. Reloaded the OwnTone integration in Home Assistant.

And suddenly everything was back to normal.

<img width="1151" alt="Screenshot 2023-11-24 at 12 37 29" src="https://github.com/owntone/owntone-server/assets/446063/33b664a5-01db-447c-9589-04c9aee57c78">

I’m not sure if this is related, but here is an earlier log entry, a few hours before I got the `JSON api request failed with error code 500` error:

```
Nov 23 02:16:52 homeserver systemd[1]: owntone.service: Main process exited, code=killed, status=9/KILL
Nov 23 02:16:52 homeserver systemd[1]: owntone.service: Failed with result 'oom-kill'.
Nov 23 02:16:52 homeserver systemd[1]: owntone.service: Consumed 45min 56.427s CPU time.
Nov 23 02:16:57 homeserver systemd[1]: owntone.service: Scheduled restart job, restart counter is at 1.
Nov 23 02:16:57 homeserver systemd[1]: Stopped DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote.
Nov 23 02:16:57 homeserver systemd[1]: owntone.service: Consumed 45min 56.427s CPU time.
Nov 23 02:16:57 homeserver systemd[1]: Started DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote.
Nov 23 02:16:58 homeserver owntone[3268147]: [2023-11-23 02:16:58] [  LOG]     main: OwnTone version 28.8 taking off
```

Let me know your take on this and if you can think of anything else for me to try in case the issue happens again. As the first action, I’ll enable debug logging.

**Comment by ejurgensen** [comment] 2023-11-24 14:07
Yes, there isn't enough info in the above to say what is causing the issue
