### ISSUE TITLE
Owntone incompatibility to Squeezelite ESP32 devices via Airplay - Buzzing

### ISSUE THREAD

**Issue by onenine2** [owntone/owntone-server#1656] opened 2023-09-23 01:15 UTC
Hello,
There seems to be an imcompatibility when using Airplay to stream to an ESP32-A1S (like [this](https://www.aliexpress.com/item/4000130915903.html)) running [Squeezelite ESP32](https://github.com/sle118/squeezelite-esp32). The ESP player appears correctly in the outputs list and can connect every time, however the audio stream has a loud buzzing on the receiver.
- The buzzing is not present when the Airplay stream is paused
- The buzzing gets louder with the Airplay volume
- I do not experience any buzzing when using Owntone to a RPi client
- The ESP32 works without buzzing when connecting via different AirPlay server software such as TuneBlade
- The ESP32 works without buzzing when streaming AirPlay from an iPhone
- I have tried changing several setting within the Owntone configuration trying different stream rates, codecs etc
- Wireshark captures from the working (TuneBlade) and Owntone stream to the ESP32 look very similar, UDP, same destination port etc
- Owntone debug logs show "Negotiated AirTunes v2 UDP streaming session DEADBEEF" when connecting to the ESP32 which does not happen with the RPi based client
- I have tried disabling Airplay 1 with the raop_disable = true and the player no longer appears
- I have tried this with forked-daapd version 27.2, owntone versions 28.6 and 28.8 
- Owntone running on a fresh RPi 3B with all packages updated to latest

Debug log attached (28.6) when connecting to the ESP. Thanks in advance.

[owntone.log](https://github.com/owntone/owntone-server/files/12705273/owntone.log)

**Comment by ejurgensen** [comment] 2023-09-24 15:10
Thanks for reporting this here. I don't have an esp32, but they look cheap and fun, so now I have ordered one :-)

I'm not sure what might be causing the buzzing, but I see the raop (Airplay 1) code in squeezeliste-esp32 is actively maintained by @philippe44 so let's try and ping him here. Philippe, might you have an idea how to debug this?

**Comment by richardsycheng** [comment] 2023-09-29 12:56
I have the same problem. But when I run iTunes on my DELL laptop, open FLAC format music from Debian OwnTone server and play it to squeezelite-esp32, it works well.

**Comment by ejurgensen** [comment] 2023-09-29 16:50
I now also have a ESP32-A1S (this [one](https://www.tinytronics.nl/shop/nl/development-boards/microcontroller-boards/met-wi-fi/ai-thinker-esp32-audio-kit-met-wi-fi-en-bluetooth)) running squeezelite-esp32, but for some reason there is no sound output, no matter what Airplay source I try with - iTunes, iPhone etc. Maybe some config I'm missing? I you guys have any hints please share.

**Comment by richardsycheng** [comment] 2023-10-01 02:41
If you can connect to the squeezelite-esp32, the ESP32-A1S, board with iTunes Airplay and able to stream music to it  but with no audio output. Its highly possible that the board doesn't work properly. Based on my personal practice, I will check the board power consumption, power management  IC output voltage, I2S signaling, DAC output and operational amplifier output to verify the device.

**Comment by onenine2** [comment] 2023-10-01 09:15
There a number of configuration parameters that will need to be experimented with the dac config. Read about them here https://github.com/sle118/squeezelite-esp32#esp32-a1s

**Comment by richardsycheng** [comment] 2023-10-01 12:08
Building the squeezelite-esp32 firmware from the source is tedious and board configuration-dependent. I do not have experience with the Ai-Thinker ESP32-A1S kit. However, I have made one for the ESP32-WROVER with TI pcm5102a DAC and amplifier. There are still some samples on hand and I can provide one as a ready-to-run Airplay device.

**Comment by ejurgensen** [comment] 2023-10-01 20:59
Well that sounds great. I still can't get mine to work. Can you write me at espenjurgensen@gmail.com to work out shipping?

**Comment by onenine2** [comment] 2023-10-02 01:44
If you got the linked A1S board you should be able to flash it from a ready made config using a Chrome based browser here https://sle118.github.io/squeezelite-esp32-installer/ . Once you have done that it should present a wifi hotspot called squeezelite with the same password. This will likely boot into recovery mode, check your IP setting and find the DHCP server address, from memory the ESP32 should host at 192.168.4.1. Go to this and adjust the audio settings, there should be a number of presets such as ES8388, try them to see if you get any sound. You will need to take it out of recovery mode to get any audio. I also found it useful to connect to it via serial in case I couldn't get it to connect to the wifi. You will also need to disable the LMS watchdog (to prevent it rebooting) by entering -disable in the server. Let me know if this still hasn't worked.

**Comment by philippe44** [comment] 2023-10-02 02:24
Did you try to play with encryption options of the owntone?

**Comment by onenine2** [comment] 2023-10-02 03:21
> Did you try to play with encryption options of the owntone?

I didn't know there were any encryption options, I did try playing various music formats and playing with the force_decode and no_decode settings without any change.

**Comment by philippe44** [comment] 2023-10-02 07:19
I don't 

> > Did you try to play with encryption options of the owntone?
> 
> I didn't know there were any encryption options, I did try playing various music formats and playing with the force_decode and no_decode settings without any change.
>
I don't know that for sure but I think my AirPlay client is expecting that, as all airplay clone do. I'd have to re-read my code. Still, it should not produce noise, instead frames should be rejected so silence only would be produced.

So, the a1s is probably not configure properly. These boards are a mess with many different versions and sometimes nothing printed on the PCB to figure out. Have a look at our SqueezeESP32 GitHub repo to have a list of some configurations we know. Look at past issues as well because more than a few people had problem with these %^¨&@! boards

**Comment by ejurgensen** [comment] 2023-10-02 21:27
I think I have found the cause of the static on the esp32. One difference between OwnTone and e.g. iTunes is that for Airplay 1, OwnTone sends an uncompressed alac stream. I tried switching to a compressed stream, and then the noise was mostly gone. You can try this by making a build from the esp32 branch I just pushed.

I believe the noise is induced by the wifi chip. An uncompressed stream approximately doubles the network throughput and means the chip is much more busy.

The compressed stream mitigates the issue, but it doesn't quite remove it. I could hear audio artifacts also when playing from my iPhone. So my overall conclusion is that the board isn't well suited for this purpose. Maybe with an external DAC it would be better.

**Comment by ejurgensen** [comment] 2023-10-05 21:22
I'm planning on switching to compressed ALAC by default, so when the above PR is merged it should also - at least partially - fix this issue

**Comment by onenine2** [comment] 2023-10-05 23:32
Thanks for all your work, I built the ESP32 fork last night and tried it to the ESP, works perfectly, not even a hint of noise. Did you get your ESP32 fully setup and working? Thanks again.

**Comment by ejurgensen** [comment] 2023-10-06 11:55
> Did you get your ESP32 fully setup and working?

It's still rebooting all the time, so I would love a hint on how to stop that. Didn't quite understand your instructions above.

**Comment by richardsycheng** [comment] 2023-10-06 12:06
For my part, I rebuilt the server from the esp32 branch and streamed music to my esp32_wrover board without any noise. Thanks for the hard work!

**Comment by onenine2** [comment] 2023-10-07 00:49
> > Did you get your ESP32 fully setup and working?
> 
> It's still rebooting all the time, so I would love a hint on how to stop that. Didn't quite understand your instructions above.

It took me a while to figure out but I am pretty sure the rebooting is a recovery feature when the connection to LMS is severed.
![image](https://github.com/owntone/owntone-server/assets/145759990/9ed5da5c-6945-4d37-97df-ffabc75e413a)

If you enter -disable in the server name of the Audio part of the web interface it should disable the connection to LMS, next reboot this field will display as 'true'. Let me know if this doesnt work.

**Comment by philippe44** [comment] 2023-10-07 02:37
if you don't want to sue LMS at all, you **must** set the server name as `-disable` per previous post. IMHO, our project is primarily made for LMS, all others are add-ons so you might be better off finding a dedicated AirPlay solution

**Closed** 2023-10-07 07:32 UTC

**Comment by ejurgensen** [comment] 2023-10-07 07:37
Thanks, that was simple enough, no more reboot now. I've merged the change now. Thanks for your help all of you, that was really awesome.
