### ISSUE TITLE
Error trying to add an Airplay1 (Shairport-Sync) target when music is playing

### ISSUE THREAD

**Issue by derekatkins** [owntone/owntone-server#1356] opened 2021-11-25 23:38 UTC
I finally got some of my OT integrations working (I'm still using the 28.2 release) and I was trying to test my setup.  I have a single machine with ~16 shairport-sync (v3.3.1) targets for all the various zones around, and I was trying to see if could actually play to all of them (short answer: no -- I need a different target to handle that much).  I started playing with about 6 streams going simultaneously (I selected 6 targets and then clicked play).  Once the music was going I tried to add another stream to another target but it failed.  I got an "Internal Error 500" on the WebUI, and the log said:
```
[2021-11-25 18:10:58] [  LOG]     raop: Send error for 'Deck': Bad file descriptor
[2021-11-25 18:10:58] [  LOG]     raop: Send error for 'Deck': Bad file descriptor
[2021-11-25 18:10:58] [  LOG]     raop: Send error for 'Deck': Bad file descriptor
[2021-11-25 18:10:58] [  LOG]     raop: Send error for 'Deck': Bad file descriptor
[2021-11-25 18:10:58] [  LOG]   player: The AirPlay 1 device 'Deck' failed to activate
[2021-11-25 18:10:58] [  LOG]      web: JSON api request failed with error code 500 (/api/outputs/47590302230029)
```
I apologize for not having debug mode turned on.  I can certainly do this if you want.

If I pause the music then I can enable the new target and restart it, but why can't I add the target while music is playing?

**Comment by ejurgensen** [comment] 2021-11-26 12:20
It should absolutely be possible to add targets during playback. It sounds like I might be able to reproduce this, which I prefer to a log, since it makes it easier to test and fix. However, I'm not totally sure about what sort of setup I should try reproducing with - can you elaborate on that?

**Comment by derekatkins** [comment] 2021-11-26 12:40
The target is a Fedora platform running shairport-sync 3.3.1.  In my setup I have a single linux box running 17 instances of shairport-sync, 16 of which go to individual speakers via USB D2A converters, and one is an alsa meta-zone to combine ~6 zones together (because I wanted to play to multiple zones from iDevices that can't send to multiple AP-1 zones).  You probably don't need that many instances to reproduce the problem.  I can send you my shairport-sync.conf files, but I would prefer not to post them here.
I started with all 16 streams activated and started playing a playlist from OT.  It sounded horrible (overloading the poor machine).  So I turned off a bunch of them (with OT still playing) until I got down to 6 streams and that worked fine.  Then I wanted to slowly add streams back in, so I tried to turn another stream back on but that's when I got the error.  When I paused OT I could re-add the zone and then start play again, but if I tried to add a zone while OT was playing I'd get the raop error.
Let me know if you need additional information.

**Comment by ejurgensen** [comment] 2021-11-26 12:55
Amazing setup! I like how you are pushing OwnTone to the limit. Going by the file descriptor message I'm thinking if the machine might actually be running out of file descriptors? I don't remember how you can check for that, but if you could Google it and check it would be good.

**Comment by derekatkins** [comment] 2021-11-26 14:08
So...
```
# cat /proc/sys/fs/file-max
9223372036854775807
```
So that's not the issue.  However logged in (as root) I get:
```
# ulimit -n
1024
```
Not sure why 1024 wouldn't be sufficient, but according to google the answer us to (re)set the DefaultLimitNOFILE in /etc/systemd/system.conf.  My system.conf currently says `#DefaultLimitNOFILE=1024:524288`, so I'm going to try increasing that to 65536:524288 and see if that makes a difference.

**Comment by derekatkins** [comment] 2021-11-26 14:13
So that increased the number of file descriptors on OT and verified when I logged in that `ulimit -n` returned 65536, but I still get the same error when trying to add a stream while it is playing.

**Comment by derekatkins** [comment] 2021-11-28 17:18
For what it's worth, I have not been able to reproduce the issue since several reboots, so I'm going to go with it was a ulimit issue.

**Comment by derekatkins** [comment] 2021-11-28 19:10
Just ran into a *different* issue:

```
Nov 28 14:06:18 owntone owntone[6053]: [2021-11-28 14:06:18] [  LOG]     raop: ANNOUNCE request failed in session startup: 453 Unauthorized
Nov 28 14:06:18 owntone owntone[6053]: [2021-11-28 14:06:18] [  LOG]   player: The AirPlay 1 device 'Den' failed to activate
Nov 28 14:06:18 owntone owntone[6053]: [2021-11-28 14:06:18] [  LOG]      web: JSON api request failed with error code 500 (/api/outputs/253201214744700)
Nov 28 14:06:25 owntone owntone[6053]: [2021-11-28 14:06:25] [  LOG]     raop: ANNOUNCE request failed in session startup: 453 Unauthorized
Nov 28 14:06:25 owntone owntone[6053]: [2021-11-28 14:06:25] [  LOG]   player: The AirPlay 1 device 'Den' failed to activate
Nov 28 14:06:25 owntone owntone[6053]: [2021-11-28 14:06:25] [  LOG]      web: JSON api request failed with error code 500 (/api/outputs/253201214744700)
```

On the Den shairport-sync server I see the following:
```
Nov 28 12:53:59 shairport shairport-sync-den[3512]: an unrecoverable error, "unable_to_cancel_play_session", has been detected.
```

This sounds like it might be a shairplay issue, although stopping play shouldn't lock it up.

**Comment by ejurgensen** [comment] 2021-11-28 20:16
Sorry, but I have to close this again. The last issue, in addition to seemingly being with shairport-sync, doesn't seem very reproducible, and thus will be impossible to analyze.

**Closed by ejurgensen** 2021-11-28 20:16 UTC

**Comment by derekatkins** [comment] 2021-11-29 12:42
Yeah, I think I'll reach out to them about that failure.  I agree, that sounds like a SP-S issue in that it doesn't reset itself.  Thanks.

**Comment by derekatkins** [comment] 2021-11-29 14:00
For the record: https://github.com/mikebrady/shairport-sync/issues/1348
