### ISSUE TITLE
[outputs/RCP soundbridge] set volume causes buffering

### ISSUE THREAD

**Issue by whatdoineed2do** [owntone/owntone-server#1449] opened 2022-04-12 13:05 UTC
> Some more data. The web page does not appear to reflect the actual volume on initial connection in all cases. If I have one Soundbridge playing, enabling a second seems to use the same volume as the currently playing Soundbridge instead of matching what the second Soundbridges volume actually is. For this to manifest, there must be more than one Soundbridge enabled. Disabling all Soundbridges and enabling each one at a time results in the correct volume being shown on the web page.
> 
> Also, I noticed that if I adjust the volume of the second Soundbridge, rebuffering occurs on all users of stream.mp3. Adjusting the volume on one Soundbridge causes rebuffering on all currently playing Soundbridges as well as a laptop streaming stream.mp3.

_Originally posted by @frankusb in https://github.com/owntone/owntone-server/issues/1389#issuecomment-1095811163_

Seems like 2 things you're raising:
1. volume change via the `OwnTone` webui, buffering occurs on `stream.mp3`
2. 2nd and subsequent soundbridges are set volume of first soundbridge

For 1) this happens in the player thread i believe and calls `rcp_device_volume_set()`  which in turn does a few checks and then a simple `writve()` to the soundbridge that the volume change was requested - if this is slow for whatever reason that blocks the player and thus causes a delay.  To verify this, you cna put some timing code around how long it takes the call to complete.  This player thread also does the sending.
https://github.com/owntone/owntone-server/blob/7598a71aea2052db97d408542aa37fbd6093b243/src/outputs/rcp.c#L1246-L1250

For 2) can you look at the rcp.c code to see what it does when a new connection is made.  The volume from the device is grabbed (`RCP_STATE_SETUP_VOL_GET` state) and provided that back to the `device` initialisation

**Comment by whatdoineed2do** [comment] 2022-04-12 15:37
FWIW, if you merge this PR https://github.com/owntone/owntone-server/pull/802 into your local branch, does it still buffer ?  This PR was specifically to give the streaming work its own thread but didnt get merged.

My own tree runs with this code.

**Comment by frankusb** [comment] 2022-04-13 23:51
Yes, assuming I merged correctly.

git fetch origin pull/802/head:httpd-streaming-evbase
git checkout httpd-streaming-evbase
autoreconf -i
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user --enable-chromecast --disable-spotify
sudo systemctl stop owntone.service
sudo cp owntone /usr/sbin/owntone
sudo systemctl start owntone.service

Most times I adjust the volume, rebuffering occurs.

**Comment by whatdoineed2do** [comment] 2022-04-14 10:21
you didnt compile the code last time - I've rebased that branch against master so it'll have the rcp/soundbridge changes.  try again with below:  note that the stream.mp3 had to move to a different port (3680) but wont affect the mdns lookup for soundbridges
```
git fetch origin pull/802/head:httpd-streaming-evbase
git checkout httpd-streaming-evbase
git --reset hard origin/httpd-streaming-evbase

autoreconf -i ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user --enable-chromecast --disable-spotify
make -j

sudo systemctl stop owntone.service 
sudo cp owntone /usr/sbin/owntone 
sudo systemctl start owntone.service
```

**Comment by frankusb** [comment] 2022-04-14 12:38
Sorry, I left that step out. I did compile.

**Comment by frankusb** [comment] 2022-04-14 13:20
Ha, does your pr produce an owntone binary? Or is it actually forked-daapd?

I checked the date of my owntone binary in the src directory and it's from 4/4. But there is a forked-daapd from 4/13. I assume my test was invalid and will retest.

**Comment by frankusb** [comment] 2022-04-14 13:22
Your PR produces forked-daapd.

> libtool: link: gcc -g -O2 -o forked-daapd

**Comment by whatdoineed2do** [comment] 2022-04-14 15:22
thats the old tree from the PR it seems - use this:
https://github.com/whatdoineed2do/forked-daapd/tree/httpd-streaming-evbase

**Comment by frankusb** [comment] 2022-04-14 21:55
The below steps result in an error on playback of the stream.

> git clone https://github.com/whatdoineed2do/forked-daapd.git
git checkout origin/httpd-streaming-evbase
autoreconf -I
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user --enable-chromecast --disable-spotify
make
sudo systemctl stop owntone.service
sudo cp src/owntone /usr/sbin/owntone 
sudo systemctl start owntone.service

/var/log/owntone shows

> [2022-04-14 16:52:34] [  LOG]    httpd: Could not dereference /usr/share/owntone/htdocs/stream.mp3: No such file or directory
[2022-04-14 16:52:35] [  LOG]    httpd: Could not dereference /usr/share/owntone/htdocs/stream.mp3: No such file or directory
[2022-04-14 16:52:36] [  LOG]    httpd: (LOGGING SKIPPED - above log message is repeating)

**Comment by whatdoineed2do** [comment] 2022-04-17 12:31
pull that branch again - the `rcp.c` explicitly builds the stream.mp3 location, incl the port (which has been moved because of the additional event base)

**Comment by frankusb** [comment] 2022-04-18 15:12
Adjusting the volume works perfectly with this version. No rebuffers and the volume is changed instantly.

The second Soundbridge enabled still shows whatever volume the first playing Soundbridge is currently set to however.

**Comment by frankusb** [comment] 2022-04-18 15:26
Regarding the volume display issue, I instrumented the code and verified that s->volume is set correctly and that s->device->volume ends up with the correct value. But the web interface does not show the correct value for the second Soundbridge. If I enable a 3rd Soundbridge, then the web interface updates the 2nd Soundbridges volume to the correct value.

**Comment by whatdoineed2do** [comment] 2022-04-18 17:34
For the buffering issue, i assume that you have a few items streaming when you adjust the volume correct?  this would suggest that the thread that is working on streaming / playing is not getting enough cycles..  the branch you using is probably not a long term solution for you and we'll need this to be considered for the master (i have other patches that i maintain in parallel so i already have a bunch of stuff outside of the upstream tree).

For the volume issue.  When the you appear to have the incorrect value, what does the REST endpoint tell you about the volume?  `curl http://yourrunningserver:3689/api/outputs`, find the correct soundbridge and use the `id` value to `curl http://yourrunningserver:3689/api/outputs/1580531867`.  If this matches the volume on your soundbirdge then theres a missing notification to the web ui.. if not, then i'm somehow not setting the volume correctly

**Comment by frankusb** [comment] 2022-04-18 18:07
The buffering does not appear to be related to the number of devices. Even with only one Soundbridge playing, the buffering occurs on most volume changes.

**Comment by frankusb** [comment] 2022-04-18 18:12
There is apparently a missing notification to the web ui.

> { "id": "2638591226", "name": "M2000 Living Room", "type": "RCP\/SoundBridge", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 100 }
<img width="320" alt="Screen Shot 2022-04-18 at 1 12 25 PM" src="https://user-images.githubusercontent.com/63519142/163853989-618e0023-a781-4977-8c94-2df55577a338.png">

**Comment by frankusb** [comment] 2022-04-20 20:44
The volume issue is not unique to RCP. Using two chromecast devices, it exhibits similar behavior.

Turn on first chromecast device, set volume to 40 or so %. Turn on second chromecast device that was previously at 100% and owntone appears to set the volume of the second chromecast to whatever the first chromecast device is currently playing at.

I went back to owntone origin/master for this experiment.

The only difference I note between Chromecast and Soundbridges is that the web page and device volume are in sync on initial connect to the Chromecast device, whereas on the Soundbridge, the web page volume matches the first playing device while the Soundbridges actual volume is not changed.

Maybe the intended behavior is that subsequent devices are set to whatever volume the first device is set to?

**Comment by frankusb** [comment] 2022-04-20 20:50
rcp_session_make does not copy the volume passed in where airplay and cast both do.

**Comment by whatdoineed2do** [comment] 2022-04-24 15:35
In the setup phase of the soundbridge, the server asks the soundbridge _what's your volume_ and the soundbrdige responds and we set that..  that info is not avialble at the point of rcp_session_make.

The chrome cast item is diferent issue and i believe intended behaviour but thats not something i've contributed to.

but what i can see is this problem:
* soundbridges have their own volume settings which i try to obey
* select soundbridge X, last know by server at vol 55, 55 is shown web ui - this is shown even if X has volume set at 88;  query on outputs endpoint shows volume as 88
* select soundbridge Y, doesnt matter volume.
   * X volume is reflected on webui (to 88 and as known internally, as evidenced by outputs endpoint)
   * Y volume is show as X's previous (incorrect) volume, 55
 
I dont know if this is somehting that's part of design.  What we can do is FORCE the soundbrdige to the volume as it was last known by the server but it should be consistent with the rest of the server.

What happens to chromecast?  if you set volume to be 10% and then restart the server,  and then select chromecast, what does server set volume for chromecast?

If you apply this patch, does this behaviour work?

```
# copy to a file /tmp/rcp.patch
# cd owntone/src
# cat /tmp/rcp.patch | patch -p1
# make

diff --git a/src/outputs/rcp.c b/src/outputs/rcp.c
index 3e8c9b739..0a46fd936 100644
--- a/src/outputs/rcp.c
+++ b/src/outputs/rcp.c
@@ -110,7 +110,7 @@ enum rcp_state
   RCP_STATE_SETUP_SERVER_CONNECT_TRANS_END,
   RCP_STATE_SETUP_SERVER_CONNECT,			// 15
 
-  RCP_STATE_SETUP_VOL_GET,
+  RCP_STATE_SETUP_VOL_SET,
 
   RCP_STATE_QUEUING_CLEAR,
   RCP_STATE_QUEUING_SET_TITLE,
@@ -168,7 +168,7 @@ static const struct rcp_state_map  rcp_state_send_map[] =
   { RCP_STATE_SETUP_SERVER_CONNECT_TRANS_END, NULL },
   { RCP_STATE_SETUP_SERVER_CONNECT, NULL },
 
-  { RCP_STATE_SETUP_VOL_GET, "GetVolume" },
+  { RCP_STATE_SETUP_VOL_SET, "SetVolume", true },
 
   { RCP_STATE_QUEUING_CLEAR, "ClearWorkingSong" },
   { RCP_STATE_QUEUING_SET_TITLE, "SetWorkingSongInfo title", true },
@@ -420,7 +420,6 @@ rcp_state_verify(struct rcp_session *s, const char *resp)
 	return 0;
       goto resp_err;
 
-    case RCP_STATE_SETUP_VOL_GET:
     case RCP_STATE_VOL_GET:
       if (strncmp(resp, "GetVolume: ", strlen("GetVolume: ")) == 0)
 	{
@@ -433,6 +432,7 @@ rcp_state_verify(struct rcp_session *s, const char *resp)
 	}
       goto resp_err;
 
+    case RCP_STATE_SETUP_VOL_SET:
     case RCP_STATE_VOL_SET:
       if (strcmp(resp, "SetVolume: OK\r\n") == 0 ||
           strcmp(resp, "SetVolume: ParameterError\r\n")  == 0)
@@ -582,11 +582,11 @@ rcp_state_transition(struct rcp_session *s)
 	break;
 
       case RCP_STATE_SETUP_SERVER_CONNECT:
-	rcp_send(s, RCP_STATE_SETUP_VOL_GET, NULL);
+	rcp_send(s, RCP_STATE_SETUP_VOL_SET, NULL);
 	break;
 
-      case RCP_STATE_SETUP_VOL_GET:
-	rcp_send(s, RCP_STATE_QUEUING_CLEAR, NULL);
+      case RCP_STATE_SETUP_VOL_SET:
+	rcp_send(s, RCP_STATE_QUEUING_CLEAR, s->device->volume);
 	break;
 
       case RCP_STATE_QUEUING_CLEAR:
@@ -807,6 +807,7 @@ rcp_session_shutdown(struct rcp_session* s, enum rcp_state state)
   event_del(s->ev);
   event_del(s->reply_timeout);
 
+  s->device->selected = 0;
   s->device->prevent_playback = 1;
 
   rcp_disconnect(s->sock);
@@ -949,6 +950,7 @@ rcp_listen_cb(int fd, short what, void *arg)
   // Downgrade state to make rcp_session_shutdown perform an exit which is
   // quick and won't require a reponse from remote
   s->state = RCP_STATE_FAILED;
+  s->device->selected = 0;
   s->device->prevent_playback = 1;
   rcp_session_shutdown(s, RCP_STATE_FAILED);
 }
@@ -964,6 +966,7 @@ rcp_reply_timeout_cb(int fd, short what, void *arg)
       DPRINTF(E_LOG, L_RCP, "Slow response from '%s' (state %d), shutting down\n", s->devname, s->state);
 
       s->state = RCP_STATE_FAILED;
+      s->device->selected = 0;
       s->device->prevent_playback = 1;
       rcp_session_shutdown(s, RCP_STATE_FAILED);
 
@@ -1052,7 +1055,7 @@ rcp_session_make(struct output_device *device, int callback_id)
 
   s->devname = strdup(device->name);
   s->address = strdup(device->v4_address);
-  s->volume = 0;
+  s->volume = device->volume;
 
   s->next = rcp_sessions;
   rcp_sessions = s;
@@ -1145,7 +1148,7 @@ rcp_status(struct rcp_session *s)
 	state = OUTPUT_STATE_STARTUP;
 	break;
 
-      case RCP_STATE_SETUP_GET_CONNECTED_SERVER ... RCP_STATE_SETUP_VOL_GET:
+      case RCP_STATE_SETUP_GET_CONNECTED_SERVER ... RCP_STATE_SETUP_VOL_SET:
       case RCP_STATE_QUEUING_CLEAR ... RCP_STATE_QUEUING_PLAY:
       case RCP_STATE_VOL_GET:
       case RCP_STATE_VOL_SET:
@@ -1198,7 +1201,8 @@ rcp_device_stop(struct output_device *device, int callback_id)
    * these need use to select (and cause the device probe to start connection to
    * remote side
    */
-  device->prevent_playback = 0;
+  device->selected = 0;
+  device->prevent_playback = 1;
 
   s->callback_id = callback_id;
   // tear this session down, incl free'ing it
@@ -1246,7 +1250,6 @@ rcp_device_volume_set(struct output_device *device, int callback_id)
 
   s->callback_id = callback_id;
 
-
   ret = snprintf(cmd, sizeof(cmd), "%d", device->volume);
   if (ret < 0) {
     return 0;
```

**Comment by frankusb** [comment] 2022-04-25 16:07
Will the server not store a volume of 100? Soundbridges that are connected to receivers should be set to 100 so that they will not alter the bitstream and the receive then adjusts the volume.

I connect to Soundbridge X, the server remembers a volume of 35. I connect to Soundbridge Y which is at 100 but the server sets it to the volume of X. I manually set the volume of Soundbridge Y to 100 (I assume the server stores this?), disconnect, reconnect and again the volume is set to 35, all within the same session of owntone.

Curiously, Soundbridge Radio Z does not exhibit this behavior but it's volume is set to 20. I can connect/disconnect and the volume of 20 is not changed.

**Comment by frankusb** [comment] 2022-04-25 16:36
Is the root issue related to master volume? It seems like the first Soundbridge sets the master volume and subsequent connections must be less than or equal to that?

**Comment by whatdoineed2do** [comment] 2022-04-25 22:53
> Is there a way to remove an old Soundbridge from the speaker list? I renamed one of my Soundbridges to eliminate a theory of why owntone was setting volumes and the new name has not gone away even after restoring the original name.
```
sqlite3 /path/to/your/songs.db
delete from speakers where name = "name of speaker to remove";
exit
```
I can't remember what conditions or whe  it stores the vol I me. It worked for  e with two test harnesses.. I changed volume j dependatly and then j slect the soundbridge to disco  dot. Next r time it connects the volume is correct.  When you start the server the soundbrises are shown in Disconnected state

**Comment by frankusb** [comment] 2022-04-26 18:53
Thank you, I have removed the test named Soundbridge.

I would think a volume of 100% is a special case for devices that are connected to external receivers. Owntone should probably not change devices that are set to 100% when owntone first connects.

I'm having difficulty parsing your response. Are you saying my test case is working for you? You can connect to a Soundbridge at something less than 100%, then connect to a second at 100% and the second is not set to the volume of the first? What is your master volume in that case?

**Comment by whatdoineed2do** [comment] 2022-04-27 09:37
> I'm having difficulty parsing your response. Are you saying my test case is working for you? You can connect to a Soundbridge at something less than 100%, then connect to a second at 100% and the second is not set to the volume of the first? What is your master volume in that case?

The scenario as seen in the web ui

|speaker|volume|selected/enabled|
|-| -:|:-:|
|master|50|yes|
|pulse|50|yes|
|rokuX|-|no|
|rokuY|-|no|

Enable one
|speaker|volume|selected/enabled|
|-| -:|:-:|
|master|60|yes|
|pulse|50|yes|
|rokuX|60|yes|
|rokuY|-|no|


Enable second
|speaker|volume|selected/enabled|
|-| -:|:-:|
|master|100|yes|
|pulse|50|yes|
|rokuX|60|yes|
|rokuY|100|yes|

Regardless of selected or not in the webui, the output of the `/api/outputs` endpoint shows the correct volume (X at 60, Y at 100)

**Comment by frankusb** [comment] 2022-04-27 12:32
The obvious difference between the examples is you enabled pulse first. I wouldn’t think that would matter though. I will try to replicate your data.

**Comment by whatdoineed2do** [comment] 2022-04-27 12:50
make sure your rcp.c is the [same as this](https://github.com/whatdoineed2do/forked-daapd/blob/master/src/outputs/rcp.c).  When you start your server and look at the speakers in the webui, you should see all the Soundbridges unselected.  Selecting them kicks off the connection/setup/handshake and the server tells the SB to set its volume at what was in the server's db (its last known volume for this speaker).

**Comment by frankusb** [comment] 2022-04-27 13:09
There were some diffs.

[rcp.c.diff.zip](https://github.com/owntone/owntone-server/files/8572180/rcp.c.diff.zip)

So I put that version in the source tree and compiled and installed it.

I start playing a playlist. Nothing is enabled and the master volume is set to 100. From the Soundbridge web interface, I can see the volume of the first is 40 and the second is 100. I enable the first, it's volume is set to 35, the master volume is set to 35 as can be verified in the Soundbridges web interface. I enable the second and it too is set to 35.

I disabled each Soundbridge, and then set each Soundbridge back to its original volumes (40/100), each has their music library set to owntone but not currently playing.

I don't have Pulse, but I have Alsa. I enable Computer and it's around 50% as is the master. I enable the first Soundbridge and it's set to 35, master remains at 50. I enable the second Soundbridge and it's set to 35 as well, master remains at 50.

I'm not sure what else to try. Remove the database and rebuild?

**Comment by frankusb** [comment] 2022-04-27 17:19
It's not a huge deal. If I'm going to enable multiple Soundbridges, I need to enable the 100 volume device first. If I forget, then I know I need to adjust the one that was set to 100 back to 100. At least now the owntone web and Soundbridge are consistent.

**Comment by whatdoineed2do** [comment] 2022-04-27 17:46
If this is good then will need input from @ejurgensen.

@ejurgensen - the original problem raised by @frankusb was related to having streams buffer whenever he adjusted volume.  I suspect this is related to 

The action of changing volume on the RCP/soundbridge is the same as the other outputs; it simply makes the request to the speaker device (its a simple `writev()` with a string `SetVolume 99\r\n` so its not this action.  What it appears to be is related to resource starvation in the thread that causes buffering.

I had PR #802 that @frankusb is now using that removes the buffering problem.

Whats your thoughts?  You open to resubmitting #802?

**Comment by ejurgensen** [comment] 2022-04-29 15:23
You're welcome to resubmit the PR, @whatdoineed2do

**Closed** 2023-03-08 23:10 UTC
