### ISSUE TITLE
100% CPU with two double quotes in smart playlist

### ISSUE THREAD

**Issue by luusl** [owntone/owntone-server#1248] opened 2021-05-16 13:19 UTC
I accidentally created a smart playlist with two double quotes in a row (`artist is ""my artist""`), whereupon the process went up to 100% CPU and the Raspberry Pi could no longer be operated. I was able to reproduce this, but only if there was a space within the quoted text. I know that the syntax is not OK, but still the whole process should not generate such a high CPU load that only a restart of the system is possible.

**Comment by ejurgensen** [comment] 2021-05-18 20:01
Yes, this doesn't sound good. I have a faint memory of this issue being mentioned before, and that it wasn't so easy to fix because it is in the antlr parser. Couldn't find it though, so not sure.

**Comment by whatdoineed2do** [comment] 2021-06-21 09:24
It's possibly this issue here https://github.com/owntone/owntone-server/issues/570.  Unfortuantely, as mentioned it appears a problem deep within the `antlr` parser but IIRC  it was not only CPU that was being maxed out but also the mem.

We did have this https://github.com/owntone/owntone-server/pull/700 PR that limited the memory using the standard `systemctl` means (ie cgroup limits).

It may be worth added a CPU limit too (process will never get more than specified quota at a time) with `CPUQuota=50%` in the `owntone.service` file and then doing:
```
systemctl daemon-reload
systemctl restart owntone
```

**Comment by ejurgensen** [comment] 2021-06-21 13:30
@whatdoineed2do do you think there is a way of preventing this from even occuring? Or at least reducing the likelihood. Maybe a pre-emptive scan of the query to sanitize quotes or something like that.

**Comment by whatdoineed2do** [comment] 2021-06-21 14:48
> @whatdoineed2do do you think there is a way of preventing this from even occuring? Or at least reducing the likelihood. Maybe a pre-emptive scan of the query to sanitize quotes or something like that.

Unfortunately not.  The OP talks about a smartpl (file) and to do preemptive as we'd be essentially have to write our own SMART pl grammar parser before throwing the file at the generated `antlr` stuff.  The flow for tiggering this is `filescan` on discovered smartpl `-> sacn_smartpl() -> smartpl_query_parse_file()`

We may be able to do something dirty on the REST endpoint that accepts smart queries/expressions but that'd be still dirty (and not the report issue above)

I was previously hit with the same `RPi` lockup issue (same problem - malformed smart query) and hence the introduction/merged cgroup/systemd max memory limits to at least contain the amount of resources the runaway process gets to consume before being killed off (and hopefully restarted) by systemd.  Odd these limits didnt stop OP's rpi from locking up though and hence a possible `CPUQuota` as another system protection band aid.

**Comment by bajinsheng** [comment] 2021-08-25 00:25
> It's possibly this issue here #570. Unfortuantely, as mentioned it appears a problem deep within the `antlr` parser but IIRC it was not only CPU that was being maxed out but also the mem.
> 
> We did have this #700 PR that limited the memory using the standard `systemctl` means (ie cgroup limits). This was done to make sure that the errors/bug in `antrl` parser would still exist but the process could not runaway with system resources RAM (making it difficult to even ssh in to kill it).
> 
> I'm a little surprised that the memory limit in the current service file didn't trap this. It may be worth added a CPU limit too (process will never get more than specified quota at a time) with `CPUQuota=50%` in the `owntone.service` file and then doing:
> 
> ```
> systemctl daemon-reload
> systemctl restart owntone
> ```

Why the memory limit does not work? My environment even exhaust 100% memory and crash.

**Comment by ejurgensen** [comment] 2021-09-03 09:48
> Why the memory limit does not work? My environment even exhaust 100% memory and crash.

The memory limit is enforced via systemd (see [the service file](https://github.com/owntone/owntone-server/blob/master/owntone.service.in)), so probably you didn't run via systemd, or you didn't have that particular service file installed. I have [made a change](https://github.com/owntone/owntone-server/commit/8c9a164c4a7512253c5e40c1a5a574a5090ca9c7) now so that service files are now installed by default, since most systems have systemd.

**Comment by bajinsheng** [comment] 2021-09-09 09:13
Is it possible to update the antlr? Does the bug exist in the latest version of antlr?

**Comment by ejurgensen** [comment] 2021-09-09 09:21
Yes and no, newest antlr with C support is 3.5.2, and the issue is present with that. However, that is from 2014, but the newer antlr4 can't generate C files. 

I think OwnTone should move away from antlr3, but it is a difficult maneuver.

BTW I made a test program to dive deeper into this: https://github.com/ejurgensen/antlrtest

**Comment by ejurgensen** [comment] 2022-01-30 09:30
Fixed with switch to bison/flex

**Closed by ejurgensen** 2022-01-30 09:30 UTC
Labels: bug
