### ISSUE TITLE
Recently added songs seems to use a random date

### ISSUE THREAD

**Issue by vasilisvg** [owntone/owntone-server#1277] opened 2021-06-19 07:28 UTC
I just upgraded from forked-daapd to Owntone and somehow I had to rebuild the library. This resulted in a reset of the list of recently added songs. This is now some sort of a random list, and it seems like this list is not really based on the date these songs/files were added.

For instance, when I do an `ls -lt` of my music directory I get a completely different, but much more accurate list.

I assume that the list in Owntone is based on the date the songs were added to the Owntone database, and that this is done when the first scan is made. So it’s not based on file-time, but on scan-time. It would be nice if somehow file modification dates could be considered during this scan as well. 

I am using Owntone 28.1 on a Raspberry Pi with an up to date Raspberry Pi Os.

**Comment by ejurgensen** [comment] 2021-07-30 23:28
Apologies for a late reply to this, but I expect you are quite right about the cause of this. I can't really think of a solution to the issue, however. I'm also thinking that there would be quite a few situations where using the file modification time would seem just as random.

So I will close this issue, but if you, or someone else. has a good suggestion on what exactly to list by I may of course reconsider.

**Closed by ejurgensen** 2021-07-30 23:28 UTC
