### ISSUE TITLE
Error opening source from spotify

### ISSUE THREAD

**Issue by beaudett** [owntone/owntone-server#1803] opened 2024-09-03 18:49 UTC
Hi,
I am currently unable to play any track from spotify with owntone Version 28.9 running on RPi 4 with bullseye. 
In the web interface, the search in spotify works. On a restart, the spotify playlists are correctly read and appear in the library. When it comes to play the tracks that I get an error. On the web interface, it appears as follows.
<img width="652" alt="Screenshot 2024-09-03 at 20 13 38" src="https://github.com/user-attachments/assets/ccb2ba9a-ec39-45d7-bc7a-5880217254db">
In the log file I see such errors:
```
[2024-09-03 20:10:19] [  LOG]  spotify: Error opening source: Cannot connect to access point, cooldown after disconnect is in effect
[2024-09-03 20:10:19] [DEBUG]  spotify: stop()
```

A longer part of the logfile can be found [here](https://gist.github.com/beaudett/a271827b10132e8a6e349092a2063900)
I am wondering if it can be a temporary problem on the spotify side ?
Thanks
Florian

**Comment by theclive** [comment] 2024-09-03 18:57
I’m currently having exactly the same problem.

sample error from the logs:

```
[2024-09-03 20:45:18] [  LOG]  spotify: Error opening source: Cannot connect to access point, cooldown after disconnect is in effect
[2024-09-03 20:45:18] [  LOG]      web: JSON api request failed with error code 500 (/api/queue/items/add?clear=true&playback=start&shuffle=false&uris=library:track:469)
```

And yet startup works fine:

```
[2024-09-03 20:44:42] [  LOG]     main: mDNS deinit
[2024-09-03 20:44:42] [  LOG]     main: Remote pairing deinit
[2024-09-03 20:44:42] [  LOG]     main: MPD deinit
[2024-09-03 20:44:42] [  LOG]     main: HTTPd deinit
[2024-09-03 20:44:42] [  LOG]     main: Player deinit
[2024-09-03 20:44:42] [  LOG]     main: Library scanner deinit
[2024-09-03 20:44:42] [  LOG]     main: Cache deinit
[2024-09-03 20:44:42] [  LOG]     main: Worker deinit
[2024-09-03 20:44:42] [  LOG]     main: Database deinit
[2024-09-03 20:44:42] [  LOG]     main: Exiting.
[2024-09-03 20:44:42] [  LOG]     main: OwnTone version 28.9 taking off
[2024-09-03 20:44:42] [  LOG]     main: Built with:
[2024-09-03 20:44:42] [  LOG]     main: - ffmpeg
[2024-09-03 20:44:42] [  LOG]     main: - Spotify
[2024-09-03 20:44:42] [  LOG]     main: - librespot-c
[2024-09-03 20:44:42] [  LOG]     main: - LastFM
[2024-09-03 20:44:42] [  LOG]     main: - Chromecast
[2024-09-03 20:44:42] [  LOG]     main: - MPD
[2024-09-03 20:44:42] [  LOG]     main: - Websockets
[2024-09-03 20:44:42] [  LOG]     main: - ALSA
[2024-09-03 20:44:42] [  LOG]     main: - Pulseaudio
[2024-09-03 20:44:42] [  LOG]     main: - Webinterface
[2024-09-03 20:44:42] [  LOG]     main: - Regex
[2024-09-03 20:44:42] [  LOG]     main: mDNS init
[2024-09-03 20:44:42] [  LOG]     mdns: Avahi state change: Client running
[2024-09-03 20:44:42] [  LOG]       db: Now vacuuming database, this may take some time...
[2024-09-03 20:44:44] [  LOG]       db: Database OK with 264 active files and 12 active playlists
[2024-09-03 20:44:44] [  LOG]   laudio: Pulseaudio failed with error: Connection refused
[2024-09-03 20:44:44] [  LOG]   laudio: Error initializing Pulseaudio: Connection refused
[2024-09-03 20:44:45] [  LOG]     scan: Scanned 200 files...
[2024-09-03 20:44:45] [  LOG]     scan: Scanned 400 files...
[2024-09-03 20:44:47] [  LOG]     scan: Bulk library scan completed in 3 sec
[2024-09-03 20:44:50] [  LOG]  spotify: Logged into Spotify succesfully with username 5butodgv0iy83aosjzhw23f76
[2024-09-03 20:44:51] [  LOG]  spotify: Scanned 1 of 5 saved playlists
[2024-09-03 20:44:52] [  LOG]  spotify: Scanned 2 of 5 saved playlists
[2024-09-03 20:44:53] [  LOG]  spotify: Scanned 3 of 5 saved playlists
[2024-09-03 20:44:54] [  LOG]  spotify: Scanned 4 of 5 saved playlists
[2024-09-03 20:44:55] [  LOG]  spotify: Scanned 5 of 5 saved playlists
[2024-09-03 20:44:55] [  LOG]  spotify: Spotify scan completed in 5 sec
[2024-09-03 20:44:56] [  LOG]      lib: Library init scan completed in 12 sec (271 changes)
```

**Comment by beaudett** [comment] 2024-09-05 21:49
Playing tracks from spotify within Owntone is working again (without changing anything).

**Comment by cmunro-godaddy** [comment] 2024-09-15 18:31
Awesome! Thank you @ejurgensen & @beaudett

**Comment by beaudett** [comment] 2024-09-18 18:55
I am sorry to say that the problem is back with the same errors in the log 
`[2024-09-18 20:36:38] [  LOG]  spotify: Error opening source: Cannot connect to access point, cooldown after disconnect is in effect`

**Comment by ejurgensen** [comment] 2024-09-19 07:55
Bummer, I would have hoped that they kept it working for longer. I will reopen.

**Comment by hacketiwack** [comment] 2024-09-19 08:05
Do you guys listen to specific tracks? I can't reproduce the problem. Maybe I don't have the same version of Spotify from where I live.

**Comment by beaudett** [comment] 2024-09-19 08:35
> Do you guys listen to specific tracks? I can't reproduce the problem. Maybe I don't have the same version of Spotify from where I live.

The problem has reappeared when I tried to play a podcast through spotify. Then I tried with one of the tracks of the same album as two weeks ago and got the same error. I will test tonight with random spotify tracks and let you know. In case the location is important, I am living in France.

**Comment by ejurgensen** [comment] 2024-09-19 08:58
I don't think there is any reason to test with specific tracks, it is more likely that it depends on the Spotify access point being used. When they roll out changes they deploy them gradually across access points. I am listening to Spotify right now with OwnTone, so there is one that works, but I can produce errors from others.

As I recall, OwnTone will try an access point, and if it fails try another one. If that fails too it will give up and you will see an error.

@alesrosina the errors you observe seem unrelated to this.

**Comment by alesrosina** [comment] 2024-09-19 08:58
> Do you guys listen to specific tracks? I can't reproduce the problem. Maybe I don't have the same version of Spotify from where I live.

Sometimes I do get an entry in log, eg:
```
spotify: Track not available for playback: 'Globi' - 'Italianità - Lied' (spotify:track:3aKQJ22gVqbSu3h09suSNu) (restrictions: { "reason": "market" })
```
But that's fine, this song is just not shown in UI and I cannot play it.

For me bigger issue is above mentioned error, which from my point of view suggest, that probably spotify implementation crashes and this is somehow not handeled in the code. But I cannot debug it.

**Comment by alesrosina** [comment] 2024-09-19 09:03
> @alesrosina the errors you observe seem unrelated to this.

I think it's related, since it's connected to spotify - and it also happens randomly. There are weeks that this works without issues and then there are some days, where this happens. And always only for spotify tracks.

So my guess here is, that there is some exception handling missing and spotify thing is crashing.

But if you think it's not related, i can open another issue.

**Comment by ejurgensen** [comment] 2024-09-19 09:48
@alesrosina what does OwnTone's log say when it fails to start playback? If it says "Error opening source: Cannot connect to access point..." then it's related. If not, then please open another issue.

**Comment by ejurgensen** [comment] 2024-09-23 18:07
@beaudett do you still experience this? It's been working fine for me the last few days.

I did start working on the new protocol, though.

**Comment by beaudett** [comment] 2024-09-23 18:32
Hi @ejurgensen 
4 days ago, the behavior was very random: some tracks were playing, some others weren't. Since then, it has been running just fine.

**Comment by ejurgensen** [comment] 2024-09-23 20:16
Ok, I will close the issue for now, let's see for how long

**Closed by ejurgensen** 2024-09-23 20:16 UTC
Labels: bug, priority
