### ISSUE TITLE
AirPlay Speakers keep turning on by themselves

### ISSUE THREAD

**Issue by braunsch** [owntone/owntone-server#1487] opened 2022-05-30 01:19 UTC
Running OwnTone 28.3 on Docker. 

Several AirPlay devices are connected to my network: 
- Apple TV
- Airport Express (old - only AirPlay 1)
- Airport Express (new - AirPlay 2)
- Denon Home speaker (AirPlay 2)
- Denon Receiver (AirPlay 2)

Once I select one of the Denon devices (no matter if in "Single" or in "Multiple" mode): I can't turn them off anymore. 
Example: I'm listening to music using the Denon receiver. A few moments later, the Denon Home speaker also comes on (but does not show as a "selected" device.
I move to a different room, choose the "Airport Express Old" (in "Single" mode - which should disconnect all other AirPlay devices). Music plays via Airport Express - but a few seconds later, the two Denon devices come on again. 

It's only the Denon devices (which officially support AirPlay 2) - and no matter what I do, I can't make them stop playing the AirPlay music. 

(the behavior is the same, no matter if I use the browser interface or the Apple Remote app to control AirPlay)

**Comment by ejurgensen** [comment] 2022-05-30 08:11
Please set the log level to debug (in `/etc/owntone.conf`) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by braunsch** [comment] 2022-05-30 22:20
Thank you for getting back to me. 

Attached is a log file in debug mode. 

Situation (all action was through iTunes Remote): 
- Speaker selection mode: Single (= picking one airplay speaker stops the previous one)
- AirPlay speaker set to "Bedroom"
- Starting to play music. Bedroom plays music, Denon Speaker is silent. 
- Switch AirPlay to "Denon Speaker". Denon speaker starts, Bedroom stops (ok - as expected). 
- Switch AirPlay back to "Bedroom". Bedroom speaker starts, Denon stops - for about 1 second - and then starts playing again. This is not expected. 
- Pause the music. 

Thank you for looking into this! 

Georg


[owntone.log](https://github.com/owntone/owntone-server/files/8800841/owntone.log)

**Comment by ejurgensen** [comment] 2022-05-31 09:22
Here's the gist of the log:

```
# Select Denon Speaker
[2022-05-30 22:09:58] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setspeakers?speaker-id=0x8ca96f038b3b&session-id=1033477223'
[2022-05-30 22:09:58] [DEBUG]     raop: device_stop: Sending TEARDOWN to 'Bedroom'
[2022-05-30 22:09:58] [DEBUG]     raop: device_start: Sending OPTIONS to 'Denon Speaker'

# Select Bedroom
[2022-05-30 22:10:15] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setspeakers?speaker-id=0x60f445e559ea&session-id=1033477223'
[2022-05-30 22:10:15] [DEBUG]     raop: device_stop: Sending TEARDOWN to 'Denon Speaker'
[2022-05-30 22:10:15] [DEBUG]     raop: device_start: Sending OPTIONS to 'Bedroom'

# Speaker sets prevent-playback (why?)
[2022-05-30 22:10:16] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=1'
[2022-05-30 22:10:16] [DEBUG]   player: Speaker prevent playback: 'Denon Speaker' (id=154659339864891)

# Speaker resets prevent-playback
[2022-05-30 22:10:16] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=0'
[2022-05-30 22:10:16] [DEBUG]   player: Speaker prevent playback: 'Denon Speaker' (id=154659339864891)

# OwnTone reacts by restarting the Denon (bug)
[2022-05-30 22:10:16] [DEBUG]     raop: device_start: Sending OPTIONS to 'Denon Speaker'
```

What's causing the issue is that the Denon Speaker - after receiving the TEARDOWN (= stop playback) - for some reason sends `device-prevent-playback=1` and then immediately `device-prevent-playback=0`. It is of course weird to ask for playback to be prevented when playback was just stopped, but still OwnTone shouldn't react by starting playback, so that is a bug.

**Comment by ejurgensen** [comment] 2022-06-02 18:07
I've attempted a fix, see the above reference. Would either of you be able to test it? It's in the branch https://github.com/owntone/owntone-server/tree/dacp_prevent_playback

**Comment by braunsch** [comment] 2022-06-03 03:28
I was trying to test it - but could not figure out how to install the
updated files (my OwnTone runs inside of a Docker container... ) :-(

--
Georg von Braunschweig
***@***.***

**Comment by aleszczynskig** [comment] 2022-06-04 13:34
Tested - seems to work correctly on the Denon.

**Comment by ejurgensen** [comment] 2022-06-06 08:22
Thanks for testing, I have merged the fix now

**Closed** 2022-06-06 08:21 UTC
Labels: bug

**Comment by oliver-koch** [comment] 2022-09-03 10:40
@ejurgensen do you have a plan for a release Build including this fix? 
I am affected By this issue too and it would be greate to get rid of it.

**Comment by ejurgensen** [comment] 2022-09-03 12:37
Sure, I can make a new release in a week or two

**Comment by oliver-koch** [comment] 2022-09-03 13:00
Sounds good. Thank you very much!

If someone has the same problem, i use the following Work-around within my home automatisation:

1. owntone Running with several airplay speakers
2. Remember active speakers. 
3. NOW i want to stop Denon device:
 A) stop owntone Playback
 B) disable denon device
 C) sleep 5s
 D) set Denon device to poweroff 
 E) start owntone Playback
 F) enanble remembered active speakers, if not automatically put to on.

**Comment by braunsch** [comment] 2022-09-10 05:28
Thank you, It seems to work now!
