### ISSUE TITLE
airplay artwork not updating

### ISSUE THREAD

**Issue by Kwinnieprince** [owntone/owntone-server#1539] opened 2022-09-27 09:51 UTC
how to reproduce:
- Start playing Spotify using spocon to a pipe
- Owntone will pick up the pipe, start playing it on airplay devices
- the metadata will only be shown for the first song, after that it stays the same and does not change.

Owntone version: 28.5

Platform: rpi

is there some kind of way to make sure the updated metadata is sent over airplay to those HomePod/airport speaker?
airplay 2 is used, not 1

**Comment by ejurgensen** [comment] 2022-09-27 13:22
Is this only when the artwork source is a pipe?

**Comment by Kwinnieprince** [comment] 2022-09-30 08:53
I only have a pipe as source so I will need to look if I can test other scenarios.

I noticed when I stop playback and start it again from owntone that the artwork updates once and then not anymore

**Comment by cdlenfert** [comment] 2022-10-02 01:39
I'm seeing the same thing when starting a Spotify playlist (shuffle enabled) directly in OwnTone.

**Comment by ejurgensen** [comment] 2022-10-11 10:19
I could reproduce this on an ATV4 with Airplay 2, but not with a Roku stick, also Airplay 2. I tried with local audio. The issue description didn't say if artwork is otherwise showing, e.g. on the web UI, but if it is then I think the issue is independent of artwork source (Spotify/pipe/local files).

The issue I observed would seem to be related to another issue, where some AP2 devices don't seem to "fully register" that they are in AP2 playback mode. So OwnTone does send metadata/artwork, but the device doesn't show it. I think this also manifests itself on Homepods, where for instance the buttons don't act as expected. I don't have Homepods myself, so this is out of memory, but I think there is another issue about it here.

I never found a solution for this, so I'm afraid that will also be the situation with this issue. I will therefore close it (also since I didn't observe any issue with pushing artwork as such).

**Closed by ejurgensen** 2022-10-11 10:19 UTC
