### ISSUE TITLE
Shairport-sync pipe iOS metadata volume sets to 0

### ISSUE THREAD

**Issue by greend139** [owntone/owntone-server#1366] opened 2021-12-11 19:09 UTC
When changing volume from iOS music app, which is playing to Shairport-sync pipe output to owntone the following is received in the logs and the volume is set to 0

Previously to building today the volume just didn't change. I have Shairport volume being ignored in Shairport-sync.conf (ignore_volume_control = "yes";)
```
daapd    | [2021-12-11 13:58:54] [DEBUG]   player: Applying Shairport metadata (type=ssnc, code=pvol, len=25)
daapd    | [2021-12-11 13:58:54] [DEBUG]   player: Not applying Shairport airplay volume while software volume control is enabled (-11.25,-18.06,-96.30,0.00)
daapd    | [2021-12-11 13:58:54] [DEBUG]   player: Status update - status: 4, events: 4, caller: volume_generic_bh
```

running owntone server built from master (d6cc0e453def1871ce776424c6505913cb2ef5a7)
shairport-sync development --with-airplay2.  (4.1-dev-101-gfbce5906-AirPlay2-alac-OpenSSL-Avahi-ALSA-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc)

Any help would be appreciated.

**Comment by ejurgensen** [comment] 2021-12-12 00:47
Thanks for notifying. Looks like I've made a regression, I will fix it asap.

**Comment by ejurgensen** [comment] 2021-12-12 09:35
I think this should be fixed now, hope you can test and verify.

**Closed** 2021-12-12 09:34 UTC
Labels: bug

**Comment by greend139** [comment] 2021-12-12 14:20
Thats for the fix!  Owntone is no longer applying the invalid metadata.
