### ISSUE TITLE
FR - Allow selecting outputs using the volume bar

### ISSUE THREAD

**Issue by spbkaizo** [owntone/owntone-server#1822] opened 2024-10-29 07:20 UTC
I tend to enable and disable audio outputs relatively often, which I achieve by the following process:

1. Click burger bar
2. Select 'Settings'
3. Select 'Remotes and Outputs'
4. Enable/Disable respective output

I'd like to be able to use the area with the volume sliders to toggle the outputs - it appears that this functionality is implemented there, but it doesn't seem as responsive or reliable as the previous method, and sometimes is a bit 'hit and miss'

In the video you can see some of the behaviour - reloading the web page will show the updated information.

https://github.com/user-attachments/assets/08930cba-765a-412a-b7f5-b5c15da67d55

**Comment by hacketiwack** [comment] 2024-11-14 10:18
@spbkaizo Thanks for having reported this. However, I tried the master version and the version 28.10, but could not reproduce your issue.
Which version are you using, and can you check if the query goes to your server?

@ejurgensen, what level of debugging should be set to check that kind of network traffic?

**Comment by ejurgensen** [comment] 2024-11-14 10:51
If the server fails to activate/deactivate a speaker, I think it will be logged with normal log level. With debug level you can see if the server is receiving a request, but I suppose you can also see the communication between server and browser from the browser's developer tools.

As I read the issue, the buttons in the settings are working, but not those in the volume bar. That could sound like a problem with websockets, so I'm wondering what platform you are running the server on? Is it MacOS?

Btw @spbkaizo, another time please follow the instructions on how to submit issues (i.e. including version/platform info + logging).

**Comment by hacketiwack** [comment] 2024-11-25 09:20
I'm closing this issue as I can't reproduce it and the reporter has not responded.

**Closed by hacketiwack** 2024-11-25 09:20 UTC
