### ISSUE TITLE
[rss] mxml doesn't return title if it has CDATA

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1677] opened 2023-10-28 08:06 UTC
Currently, the metadata of a podcast seems to be taken from the individual files linked to each podcast episode.
RSS feeds for podcasts provide, indeed, a tag `enclosure`, which has an attribute `url` pointing to the aforementioned file.

Even if this seems legitimate to read information from this file, it appears, however, that some podcasters don't tag their episodes and therefore, taking the information from the feed would be more advisable in this situation.

This results in quite ugly displays in the web interface (example below).

<img width="1084" alt="Incorrect display of RSS feeds" src="https://github.com/owntone/owntone-server/assets/13329768/4441130d-942e-4734-a9ed-c73226ed0f56">

An example of such a podcast feed is this [one](https://anchor.fm/s/1733e28c/podcast/rss).

This work item is not 100% an issue, it is more an unsightliness.

**Comment by ejurgensen** [comment] 2023-11-04 08:56
It looks like the cause is that this RSS has CDATA in the title, which for some reason makes the xml parser library unable to read the tag:
`<title><![CDATA[013. Q&A - Qu'est-ce qui relève de ma personnalité vs ce que je peux changer? ]]></title>`

Not sure if it is a bug in the library or if owntone should be calling it differently. Or if it is invalid xml.

**Comment by ejurgensen** [comment] 2023-11-17 10:34
Thanks for reporting this, should be fixed now. Looking at this seemingly small problem opened a can of XML-worms that I wouldn't otherwise have thought about, so at the very least I am now a bigger fan of json. These worms could lead to issues other places in OwnTone where XML is processed, but hopefully that is also fixed with the above PR.

**Closed by ejurgensen** 2023-11-17 10:34 UTC
Labels: bug

**Comment by hacketiwack** [comment] 2023-11-17 15:53
Thanks for the fix and sorry for the occasioned trouble.
