### ISSUE TITLE
[web] new feature suggestion of filter switch

### ISSUE THREAD

**Issue by beaudett** [owntone/owntone-server#1650] opened 2023-09-07 19:33 UTC
Hello ! 
in the "Music/Artists" tab of the web interface, there is a convenient "Hide artists from Spotify" switch and I am wondering if it could be implemented within the album view (I mean what you see at http://owntone.local:3689/#/music/albums/XXXXXXXX) as well. 
Let me explain the use case: some titles are duplicated in my library because they are both on disk and in a spotify playlist, where they have been included to be able to listen on portable devices. The consequence is that in the album view, some tracks are present twice and would get played twice when adding the entire album in the queue. See the illustration below:
<img width="1024" alt="Screenshot 2023-09-07 at 21 29 35" src="https://github.com/owntone/owntone-server/assets/4553043/881368d1-fc7d-433a-aab7-4d47b3857198">
The first occurrence of the title corresponds to the file on disk while the second in the Spotify track. 
Thanks again for this great software ! 
Florian

**Comment by hacketiwack** [comment] 2023-09-07 20:18
I will check that out. But it's certainly possible.

**Comment by hacketiwack** [comment] 2023-09-07 20:50
I checked this situation on my side and couldn't reproduce it.
If I include an album from Spotify, it will get another identifier and won't be mixed with the "same" album I have on my file system.
Did you do something specific to have all the tracks - from Spotify and your file system - to have them under the same album?

Let's say that I have an album **A** from artist **B**.
Let's also assume I have the album on my file system under the identifier [6261546424352019694](http://owntone.local:3689/#/music/albums/6261546424352019694).
If I have the same album from Spotify, it will have another identifier: e.g [657633320303602900](http://owntone.local:3689/#/music/albums/657633320303602900)

Therefore, I don't see how - or I don't know how - to make this situation happen.
Can you please tell me a bit more precisely how you did ended up in such situation?
Could it be that you have the tracks twice in your file system? Can you check the source under each tracks in the example you mention?

Thanks in advance.

**Comment by beaudett** [comment] 2023-09-07 21:17
Hi @hacketiwack 

thank you for the prompt reply and interest ! 
The entire album is on disk in the owntone library. A subset of the tracks of this album has been picked up in Spotify  and put in a "favorite" songs Spotify playlist. The latter has been done from the Spotify application. 
As far as I can see, the source of the tracks is different (see below). 
I can deduce the identifier from the version on disk from the URL and it is 4618382931502290393; but I can't see the same album in its Spotify version (unless I do specific search from the dedicated spotify tab of course) but for sure I can't find any identifier for it. 

<img width="789" alt="Screenshot 2023-09-07 at 22 54 15" src="https://github.com/owntone/owntone-server/assets/4553043/017b6926-8fc5-4ad3-a995-02e3b20debf9">
<img width="885" alt="Screenshot 2023-09-07 at 22 54 33" src="https://github.com/owntone/owntone-server/assets/4553043/62e3138a-68c0-424a-a50c-f9eaa79101c8">

I take the opportunity to mention that I am using Version 28.6 on a RaspberryPi. 
Thanks !

**Comment by ejurgensen** [comment] 2023-09-10 21:11
Another way of fixing this might be to include the data_kind in the creation of the album and artist id's. Then the Spotify tracks and the filesystem tracks would be shown as separate albums. I have a vague recollection that this has been discussed here on github before, maybe there are some cons to this I don't quite remember. Could be that it wouldn't be immediately clear why the same album/artists appear twice.

**Comment by hacketiwack** [comment] 2023-12-17 17:39
I finally understood why on your library, @beaudett, you had Spotify and local items in the same album.
Actually, this is based on the grouping done by OwnTone. If there is no differentiation other than the album title and artist name, then Spotify and local tracks are "merged" together in one album.

To prevent this, I highly recommend that you tag your files with a tool like [MusicBrainz Picard](https://picard.musicbrainz.org), which will add an album identifier on your tracks. Thus, preventing an "accidental" merge. when scanning the library.

What would be the ideal situation is that OwnTone would just separate local and Spotify tracks in different albums.
From a logical point of view, they are different releases of the same album (according to MusicBrainz and Discogs definition of an album release).
@ejurgensen do you think this could be easily feasible? It would basically mean to not group Spotify albums with local library albums.

In the meantime, I added a filter on the page "Artist Albums" and "Artist Tracks" to give the possibility to filter out Spotify content. I hope this helps for now. But, this doesn't filter out Spotify tracks on the Album page though and is still imperfect in terms of calculating the number of tracks for an album.
We could add a filter on the Album page. However, IMHO, we would just solve the problem from a UI point of view, which is kind of ugly. Added to that, the Album page is not really fitted to have filters.

**Comment by beaudett** [comment] 2023-12-17 20:15
Hi @hacketiwack. Thank you so much for investigating the issue ! Indeed, I can confirm that running picard on the directory (I just checked with one so far) does the trick: the tracks get split into two different "albums", one corresponding to the local library, the other one to Spotify. I am fine with this behavior as it prevents from playing twice the same track when listening to an album.  For my education, what is the tag added by picard that allows owtone to disentangle between the two tracks ?

**Comment by ejurgensen** [comment] 2023-12-17 20:19
> do you think this could be easily feasible? It would basically mean to not group Spotify albums with local library albums.

Yes, it should be easy enough, I think the above commit should do that. It does require a rescan, because the album id's have to be recalculated. Hope either of you can test it.

**Comment by hacketiwack** [comment] 2023-12-17 20:27
Thanks @ejurgensen I will test it in the coming hours.

@beaudett, the tags that are coming from MusicBrainz Picard and used by OwnTone are [those](https://github.com/owntone/owntone-server/blob/master/src/library/filescanner_ffmpeg.c#L208), but mainly this one: "MusicBrainz Album Id".

**Comment by hacketiwack** [comment] 2023-12-18 12:14
I tested the change and now the Spotify and the album from the local library are split.
Thanks for the fix @ejurgensen.

**Closed by hacketiwack** 2023-12-18 12:14 UTC

**Comment by ejurgensen** [comment] 2023-12-18 12:35
Great, thanks for the quick test :-)
