### ISSUE TITLE
Spotify tracks interrupted

### ISSUE THREAD

**Issue by beaudett** [owntone/owntone-server#1745] opened 2024-04-07 14:54 UTC
Hi, 

I first would like to thank you for this great software. I am running the Version 28.9 on a RPI-4 installed as described [here](https://www.raspberrypi.org/forums/viewtopic.php?t=49928). The problem I encounter is the following. 
Some tracks read from Spotify are stopped after about two/three minutes. Contrary to what has been reported [here](https://github.com/owntone/owntone-server/issues/1739) (and that I also saw happening some days ago), the player has moved to the next item on the playlist three times until it finally cleared the playlist and it put owntone in a bad state where the webinterface had become non responsive. As matter of fact, I saw from the log that owntone restarted, it must had crashed.
In the log file, one sees such errors also different from that reported in the issue 1739. 
```
[2024-04-07 16:10:56] [  LOG]   player: Error reading source 'spotify:track:69bzKh6IzsoKvSniWmstjF' (id=9999999)
```
followed by 
```
[2024-04-07 16:07:43] [  LOG]   player: Error reading from source
```
The DEBUG log of owntone of two consecutive occurrences of the problem can be found [here](https://gist.github.com/beaudett/51c24c8eb980fb371a5c202373896757)

To give an idea of the frequency 
```
grep "Error reading from source" /var/log/owntone.log
[2024-04-07 16:07:43] [  LOG]   player: Error reading from source
[2024-04-07 16:10:56] [  LOG]   player: Error reading from source
[2024-04-07 16:13:39] [  LOG]   player: Error reading from source
```

The album I was playing was [this one](https://open.spotify.com/album/0RQPuyaKyrEG8lSkl089zC?si=G1hiFCUtQ2u3LgJQWPLaXw) which I was playing directly from the "search" tab of the webinterface, i.e. it is not in my library. 

Let me know if I should provide you with more information.

**Comment by hacketiwack** [comment] 2024-04-07 14:58
@beaudett, I experienced the same behaviour you described. It leads indeed to OwnTone become unresponsive and finally crashing.

**Comment by ejurgensen** [comment] 2024-04-07 19:35
I'm pretty sure this is duplicate of #1739 so I will close this one

**Closed by ejurgensen** 2024-04-07 19:35 UTC
Labels: duplicate
