### ISSUE TITLE
Smart playlists sometimes disappear

### ISSUE THREAD

**Issue by vasilisvg** [owntone/owntone-server#1347] opened 2021-11-19 22:20 UTC
I find this a bit hard to reproduce, but every now and then the smart playlists disappear from the list of playlists, both in the webplayer and in apps like Apple Remote and Rigelian on iOS. The only way I found to fix this is to remove all smart playlists from the playlist folder, and then adding them again after updating the library. 

Unfortunately I haven't been able to figure out when and why this happens. But it has happened a few times now. And I don’t really know how to debug this. Any tips on what might cause this issue so I can try to force it? And any ideas on how I can best try to log this issue to figure out what causes it?

There are a bit over 11.000 songs, stored on disk, in this OwnTone library. And there are many more songs in this library via Spotify. 
Right now there is a total of 104 playlists. 18 smart playlists, 29 m3u playlists with relative paths, and the rest of them are Spotify playlists. Playlists vary in size from 20 to thousands of songs.

I am running OwnTone 28.2 on a Raspberry Pi 3B+ on an up to date Raspbian Lite 10 (buster). It is a pretty minimal installation with only Owntone, Shairport Sync and Raspotify running.

**Comment by ejurgensen** [comment] 2021-11-20 09:54
There are multiple ways playlists can get deleted or disabled. As far as I can tell via mpd, json api, a filesystem event or a library rescan. Normally I would suggest setting the log level to debug, because then you can trace what triggered it (search for the name of the disappeared playlist). However, since your library is large and the issue is infrequent the log will become very large. So you will probably want to clear it often. You can do that with e.g. `echo reset > /var/log/owntone.log`, maybe as temporary cron job while you debug.

**Comment by vasilisvg** [comment] 2021-11-20 11:03
Maybe I should to clarify the issue a bit more: the smart playlists are not deleted from the filesystem, they are still there. They just don’t show up in the OwnTone library anymore. And *all smart playlists* are affected, and not any other playlists. 
I'll set the logs to debug level, and I'll set a cronjob, and I'll wait until it happens again.

**Comment by ejurgensen** [comment] 2021-12-12 13:06
Closing this until further info.

**Closed by ejurgensen** 2021-12-12 13:06 UTC
